name: Run dbt project on commit

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH connection
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Run dbt
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} "\
        cd ${{ secrets.DBT_REPO_PATH }} && \
        git pull && \
        source venv/bin/activate && \
        dbt run && \
        superset-cli -u ${{ secrets.SUPERSET_USER }} -p ${{ secrets.SUPERSET_PW }} ${{ secrets.SUPERSET_URL }} sync dbt-core ${{ secrets.DBT_REPO_PATH }}/target/manifest.json --project=spotify --target=superset --profiles=/root/.dbt/profiles.yml --import-db --disallow-edits --select=${{ secrets.DBT_MODELS_PATH }}/models/marts/* \
        "